apiVersion: v2
name: kube-guardian
description: A Helm chart for Kubernetes
home: https://xentra.ai/

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.27

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 0.0.11
kubeVersion: ">= 1.18.0-0"

keywords:
  - BPF
  - eBPF
  - Kubernetes
  - Networking
  - Security
  - Observability
  - Troubleshooting

sources:
  - https://github.com/xentra-ai/kube-guardian

maintainers:
  # Mahesh Rayas
  - name: maheshrayas
    email: mahesh.rayas@xentra-ai.com
  # Michael Fornaro
  - name: xunholy
    email: michael.fornaro@xentra-ai.com
